// Cars to add: EV9, Titan, F-150, Silverado, W9, R2

// NEED TO ADD MORE OLDSMOBILES, MERCURYS, 

// 'Fury MK4|15000|XXXXX|P','F-150 MK12|15000|XXXXX|P','F-150 MK13|25000|XXXXX|P','Duster|35000|XXXXX|P','Satellite MK1|35000|XXXXX|P','Satellite MK2|35000|XXXXX|P','Satellite MK3|35000|XXXXX|P','Le Baron MK2|10000|XXXXX|P','E-Type Series I Roadster|105000|JA004|S','E-Type Series II Roadster|65000|JA004|A',E-Type Series III Coupe|40000|JA005|P',E-Type Series III Roadster|65000|JA005|A'

/*
'Labrador Retriever',
'French Bulldog',
'Golden Retriever',
'German Shepherd',
'Poodle',
'Dachshund',
'Beagle',
'Rottweiler',
'Pembroke Welsh Corgi',
'German Shorthaired Pointer',
'Yorkshire Terrier',
'Boxer',
'Australian Shepherd',
'Siberian Husky',
'Cavalier King Charles Spaniel',
'Doberman Pinscher',
'Shih Tzu',
'Great Dane',
'Miniature Schnauzer',
'Bernese Mountain Dog',
'Boston Terrier',
'Brittany',
'Cane Corso',
'Basset Hound',
'English Springer Spaniel',
'Border Collie',
'Chihuahua',
'Belgian Malinois',
'Newfoundland',
'Collie',
'West Highland White Terrier',
'Rhodesian Ridgeback',
'Bichon Frise',
'Mastiff',
'Portuguese Water Dog',
'Weimaraner',
'Vizsla',
'Pug',
'Bloodhound',
'Bull Terrier',
'Akita',
'Alaskan Malamute',
'Samoyed',
'Papillon',
'Whippet',
'Italian Greyhound',
'Scottish Terrier',
'Irish Setter',
'Bullmastiff',
'Chinese Shar-Pei',
'St. Bernard',
'English Cocker Spaniel',
'Great Pyrenees',
'Dalmatian',
'Australian Cattle Dog',
'Soft Coated Wheaten Terrier',
'Airedale Terrier',
'Basenji',
'Norwegian Elkhound',
'Wirehaired Pointing Griffon',
*/

/*
'Goldendoodle',
'Labradoodle',
'Cockapoo',
'Cavapoo',
'Maltipoo',
'Pomsky',
'Schnoodle',
'Yorkipoo',
'Chiweenie',
'Morkie',
'Puggle',
'Bernedoodle',
'Sheepadoodle',
'Aussiedoodle',
'Shih-Poo',
'Chorkie',
'Havapoo',
'Cavachon',
'Boxador',
*/